services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    expose:
      - 8080
    networks:
      - DA-net
    env_file:
      - ./backend/.env
    depends_on:
      - elastic
    develop:
      watch:
        - action: rebuild
          path: ./backend
  elastic:
    build: ./elastic
    container_name: elastic
    expose:
      - 9200
    networks:
      - DA-net
    env_file:
      - ./elastic/.env
    volumes:
      - esdata:/usr/share/elasticsearch/data
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    expose:
      - 5173
    networks:
      - DA-net
    develop:
      watch:
        - action: rebuild
          path: ./frontend
  init-elastic:
    build:
      context: ./init-elastic
      dockerfile: Dockerfile
    container_name: init-elastic
    networks:
      - DA-net
    env_file:
      - ./init-elastic/.env
    depends_on:
      - elastic
  proxy:
    build:
      context: ./proxy
      dockerfile: Dockerfile
    container_name: proxy
    ports:
      - "80:80"
      - "443:443"
    networks:
      - DA-net
    depends_on:
      backend:
        condition: service_started
      frontend:
        condition: service_started
      init-elastic:
        condition: service_completed_successfully
    security_opt:
      - no-new-privileges:true
  tests:
    profiles:
      - tests
    build:
      context: ./tests
      dockerfile: Dockerfile
    container_name: tests
    networks:
      - DA-net
    depends_on:
      proxy:
        condition: service_started

volumes:
  esdata:

networks:
  DA-net:
    driver: bridge