services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    expose:
      - 8080
    networks:
      - all-net
      - es-net
      - rs-net
    secrets:
      - backend.yaml
    env_file:
      - ./configs/backend.env
    depends_on:
      - elastic
      - redis
    develop:
      watch:
        - action: rebuild
          path: ./backend
  elastic:
    image: elasticsearch:9.3.1
    container_name: elastic
    expose:
      - 9200
    networks:
      - es-net
    env_file:
      - ./configs/elastic.env
    volumes:
      - esdata:/usr/share/elasticsearch/data
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    expose:
      - 5173
    networks:
      - all-net
    configs:
      - source: frontend
        target: /etc/nginx/conf.d/default.conf
    develop:
      watch:
        - action: rebuild
          path: ./frontend
  init-elastic:
    build:
      context: ./init-elastic
      dockerfile: Dockerfile
    container_name: init-elastic
    networks:
      - es-net
    configs:
      - source: init-elastic
        target: /etc/init-elastic.yaml
    depends_on:
      - elastic
  
  redis: # Ес чо, он ругается на то, что по дэфолту в linux планировщик сильно переживает за память. Настраивается на хосте. Нам вроде как пока плевать, если начнет падать, мол, не могу сохранить дамп, то просто увеличить память
    image: redis:8.6.2-alpine3.23
    container_name: redis
    expose:
      - 6379
    networks:
     - rs-net
    configs:
      - source: redis
        target: /usr/local/etc/redis/redis.conf
    secrets:
      - redis-sec.acl
    volumes:
      - rsdata:/data
    command: redis-server /usr/local/etc/redis/redis.conf
  proxy:
    image: nginx:1.29.4-alpine3.23
    container_name: proxy
    ports:
      - "80:80"
      - "443:443"
    networks:
      - all-net
    configs:
      - source: proxy
        target: /etc/nginx/nginx.conf
    secrets:
      - proxy.crt
      - proxy.key
    depends_on:
      backend:
        condition: service_started
      frontend:
        condition: service_started
      init-elastic:
        condition: service_completed_successfully
    security_opt:
      - no-new-privileges:true
  tests:
    profiles:
      - tests
    build:
      context: ./tests
      dockerfile: Dockerfile
    container_name: tests
    networks:
      - all-net
      - rs-net
      - es-net
    depends_on:
      proxy:
        condition: service_started

configs:
  frontend:
    file: ./configs/frontend.conf
  init-elastic:
    file: ./configs/init-elastic.yaml
  proxy:
    file: ./configs/proxy.conf
  redis:
    file: ./configs/redis.conf

secrets:
  proxy.crt:
    file: ./secrets/proxy.crt
  proxy.key:
    file: ./secrets/proxy.key
  backend.yaml:
    file: ./secrets/backend.yaml
  redis-sec.acl:
    file: ./secrets/redis-sec.acl

volumes:
  esdata:
  rsdata:

networks:
  all-net:
    driver: bridge
  rs-net:
    driver: bridge
  es-net:
    driver: bridge