CREATE TABLE IF NOT EXISTS "Team" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"name" VARCHAR(255) NOT NULL UNIQUE,
	PRIMARY KEY("id")
);




CREATE TABLE IF NOT EXISTS "Student" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"name" VARCHAR(255) NOT NULL,
	"team_id" INTEGER NOT NULL,
	PRIMARY KEY("id")
);




CREATE TABLE IF NOT EXISTS "Service" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"name" VARCHAR(255) NOT NULL UNIQUE,
	"team_id" INTEGER NOT NULL,
	PRIMARY KEY("id")
);




CREATE TABLE IF NOT EXISTS "Achievement" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"name" VARCHAR(255) NOT NULL UNIQUE,
	PRIMARY KEY("id")
);




CREATE TABLE IF NOT EXISTS "AchievementTeam" (
	"team_id" INTEGER NOT NULL,
	"achievement_id" INTEGER NOT NULL,
	"timestamp" TIMESTAMP NOT NULL,
	PRIMARY KEY("team_id", "achievement_id")
);




CREATE TABLE IF NOT EXISTS "ApiKey" (
	"service_id" INTEGER NOT NULL,
	"key" VARCHAR(255) NOT NULL,
	PRIMARY KEY("service_id", "key")
);




CREATE TABLE IF NOT EXISTS "Authorization" (
	"login" VARCHAR(255) NOT NULL UNIQUE,
	"password" VARCHAR(255) NOT NULL,
	"team_id" INTEGER NOT NULL,
	PRIMARY KEY("login")
);




CREATE TABLE IF NOT EXISTS "GitCommit" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"timestamp" TIMESTAMP NOT NULL,
	"student_id" INTEGER NOT NULL,
	"description" TEXT,
	PRIMARY KEY("id")
);



ALTER TABLE "Student"
ADD FOREIGN KEY("team_id") REFERENCES "Team"("id")
ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE "Authorization"
ADD FOREIGN KEY("team_id") REFERENCES "Team"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "AchievementTeam"
ADD FOREIGN KEY("team_id") REFERENCES "Team"("id")
ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE "Service"
ADD FOREIGN KEY("team_id") REFERENCES "Team"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "ApiKey"
ADD FOREIGN KEY("service_id") REFERENCES "Service"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "AchievementTeam"
ADD FOREIGN KEY("achievement_id") REFERENCES "Achievement"("id")
ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE "GitCommit"
ADD FOREIGN KEY("student_id") REFERENCES "Student"("id")
ON UPDATE CASCADE ON DELETE CASCADE;


-- Constraints for Student's name
ALTER TABLE "Student" 
ADD CONSTRAINT "student_name_not_empty" 
CHECK (trim("name") != '');

-- Constraints for Authorization (login - only letters and numbers)
ALTER TABLE "Authorization" 
ADD CONSTRAINT "login_alphanumeric" 
CHECK ("login" ~ '^[a-zA-Z0-9]+$');

ALTER TABLE "Authorization" 
ADD CONSTRAINT "password_min_length" 
CHECK (length("password") >= 8);

-- Constraints for Team's name (only letters)
ALTER TABLE "Team" 
ADD CONSTRAINT "team_name_alpha_only" 
CHECK ("name" ~ '^[a-zA-Z]+$');

-- Constraints for Service's name (only letters)
ALTER TABLE "Service" 
ADD CONSTRAINT "service_name_alpha_only" 
CHECK ("name" ~ '^[a-zA-Z]+$');

-- Constraints for Achievement's name (can contain letters, numbers, and spaces)
ALTER TABLE "Achievement" 
ADD CONSTRAINT "achievement_name_valid_chars" 
CHECK ("name" ~ '^[a-zA-Z0-9 ]+$');

-- Constraints for AchievementTeam (timestamp defaults to current time)
ALTER TABLE "AchievementTeam" 
ALTER COLUMN "timestamp" SET DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE "AchievementTeam" 
ADD CONSTRAINT "achievement_timestamp_not_future" 
CHECK ("timestamp" <= CURRENT_TIMESTAMP);


