CREATE TABLE IF NOT EXISTS "Team" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"name" VARCHAR(255) NOT NULL UNIQUE,
	PRIMARY KEY("id")
);




CREATE TABLE IF NOT EXISTS "Student" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"name" VARCHAR(255) NOT NULL,
	"team_id" INTEGER NOT NULL,
	PRIMARY KEY("id")
);




CREATE TABLE IF NOT EXISTS "Service" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"name" VARCHAR(255) NOT NULL UNIQUE,
	"team_id" INTEGER NOT NULL,
	PRIMARY KEY("id")
);





CREATE TABLE IF NOT EXISTS "ApiKey" (
	"service_id" INTEGER NOT NULL,
	"key" VARCHAR(255) NOT NULL,
	PRIMARY KEY("service_id", "key")
);




CREATE TABLE IF NOT EXISTS "Authorization" (
	"login" VARCHAR(255) NOT NULL UNIQUE,
	"password" VARCHAR(255) NOT NULL,
	"team_id" INTEGER NOT NULL,
	PRIMARY KEY("login")
);




ALTER TABLE "Student"
ADD FOREIGN KEY("team_id") REFERENCES "Team"("id")
ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE "Authorization"
ADD FOREIGN KEY("team_id") REFERENCES "Team"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE "Service"
ADD FOREIGN KEY("team_id") REFERENCES "Team"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE "ApiKey"
ADD FOREIGN KEY("service_id") REFERENCES "Service"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;


-- Constraints for Student's name
ALTER TABLE "Student" 
ADD CONSTRAINT "student_name_not_empty" 
CHECK (trim("name") != '');

-- Constraints for Authorization 
-- Login: letters, numbers, and special characters
ALTER TABLE "Authorization" 
ADD CONSTRAINT "login_valid_chars" 
CHECK ("login" ~ '^[a-zA-Z0-9!@#$%^&*()_+\-=\[\]{};:\\|,.<>\/?]+$');

ALTER TABLE "Authorization" 
ADD CONSTRAINT "password_min_length" 
CHECK (length("password") >= 8);

ALTER TABLE "Authorization" 
ADD CONSTRAINT "password_valid_chars" 
CHECK ("password" ~ '^[a-zA-Z0-9!@#$%^&*()_+\-=\[\]{};:\\|,.<>\/?]+$');

-- Constraints for Team's name (only letters)
ALTER TABLE "Team" 
ADD CONSTRAINT "team_name_alpha_only" 
CHECK ("name" ~ '^[a-zA-Z]+$');

-- Constraints for Service's name (only letters)
ALTER TABLE "Service" 
ADD CONSTRAINT "service_name_alpha_only" 
CHECK ("name" ~ '^[a-zA-Z]+$');

