bind 0.0.0.0
protected-mode yes
enable-protected-configs no
enable-debug-command no
enable-module-command no
port 6379
tcp-backlog 511
timeout 10
tcp-keepalive 300
daemonize no
loglevel notice

# stdout
logfile ""

# numeric prefixes is so hard for brain. We will use 1 database and different prefixes in keys
databases 1

always-show-logo no

# It's default. I don't want change
set-proc-title yes
proc-title-template "{title} {listen-addr} {server-mode}"

locale-collate ""

#snapshotting
save 60 1
save 30 500
save 10 10000
stop-writes-on-bgsave-error yes
rdbcompression yes
rdbchecksum yes
dbfilename dump.rdb
dir /data

#security
aclfile /run/secrets/redis-sec.acl

maxclients 100
maxmemory 200mb
maxmemory-policy allkeys-lru
maxmemory-samples 5
active-expire-effort 1
maxmemory-eviction-tenacity 10
lazyfree-lazy-eviction yes
lazyfree-lazy-expire yes
lazyfree-lazy-server-del yes